services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: helpdesk
      POSTGRES_PASSWORD: helpdesk
      POSTGRES_DB: helpdesk
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - helpdesk-net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U helpdesk -d helpdesk" ]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    networks:
      - helpdesk-net
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 10

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - helpdesk-net
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 30s

  auth-service:
    build: ./auth-service
    environment:
      KEYCLOAK_URL: http://keycloak:8080
      KEYCLOAK_REALM: helpdesk
    depends_on:
      - keycloak
    ports:
      - "8001:8001"
    networks:
      - helpdesk-net

  ticket-api:
    build: ./ticket-api
    environment:
      POSTGRES_USER: helpdesk
      POSTGRES_PASSWORD: helpdesk
      POSTGRES_DB: helpdesk
      POSTGRES_HOST: db

      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0

      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: user
      RABBITMQ_PASS: password
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    ports:
      - "8000:8000"
    networks:
      - helpdesk-net

  frontend:
    build: ./frontend
    environment:
      AUTH_URL: http://auth-service:8001
      API_URL: http://ticket-api:8000
    depends_on:
      - auth-service
      - ticket-api
    ports:
      - "8501:8501"
    networks:
      - helpdesk-net

  worker:
    build: ./worker
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: user
      RABBITMQ_PASS: password
      BACKEND_URL: http://ticket-api:8000
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - helpdesk-net

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.2
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command:
      - start-dev
      - --import-realm
    ports:
      - "8080:8080"
    networks:
      - helpdesk-net
    volumes:
      - keycloak_data:/opt/keycloak/data
      - ./keycloak/helpdesk-realm.json:/opt/keycloak/data/import/helpdesk-realm.json:ro

  kong:
    image: kong:3.6
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /etc/kong/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
      KONG_PROXY_LISTEN: "0.0.0.0:8000"
    volumes:
      - ./kong/kong.yml:/etc/kong/kong.yml:ro
    ports:
      - "8100:8000"
      - "8101:8001"
    depends_on:
      - ticket-api
      - auth-service
    networks:
      - helpdesk-net
    healthcheck:
      test: [ "CMD", "kong", "health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@helpdesk.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - helpdesk-net
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
  keycloak_data:
  pgadmin_data:

networks:
  helpdesk-net:
    driver: bridge
