services:
  auth-service:
    image: helpdesk-distributed-auth-service:latest
    environment:
      KEYCLOAK_URL: http://keycloak:8080
      KEYCLOAK_REALM: helpdesk
    ports:
      - "8001:8001"
    networks:
      - helpdesk-net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  ticket-api:
    image: helpdesk-distributed-ticket-api:latest
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: helpdesk
      POSTGRES_USER: helpdesk
      POSTGRES_PASSWORD: helpdesk

      REDIS_HOST: redis
      REDIS_PORT: 6379

      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: user
      RABBITMQ_PASS: password
    networks:
      - helpdesk-net
    ports:
      - "8000:8000"
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      update_config:
        order: start-first
        parallelism: 1
        delay: 3s


  frontend:
    image: helpdesk-distributed-frontend:latest
    environment:
      AUTH_URL: http://auth-service:8001
      API_URL: http://ticket-api:8000

    networks:
      - helpdesk-net

    ports:
      - "8501:8501"

    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure


  worker:
    image: helpdesk-distributed-worker:latest
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: user
      RABBITMQ_PASS: password
      QUEUE_NAME: ticket_events
      BACKEND_URL: http://ticket-api:8000

    networks:
      - helpdesk-net

    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure


  db:
    image: postgres:15
    environment:
      POSTGRES_DB: helpdesk
      POSTGRES_USER: helpdesk
      POSTGRES_PASSWORD: helpdesk

    volumes:
      - db_data:/var/lib/postgresql/data

    networks:
      - helpdesk-net

    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure


  redis:
    image: redis:7-alpine

    networks:
      - helpdesk-net

    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure


  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

    ports:
      - "5672:5672"
      - "15672:15672"

    networks:
      - helpdesk-net

    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure


  keycloak:
    image: quay.io/keycloak/keycloak:24.0.2
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command:
      - start-dev
      - --import-realm

    ports:
      - "8080:8080"

    volumes:
      - keycloak_data:/opt/keycloak/data
    configs:
      - source: helpdesk_realm
        target: /opt/keycloak/data/import/helpdesk-realm.json

    networks:
      - helpdesk-net

    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure


  kong:
    image: kong:3.6
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /etc/kong/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
      KONG_PROXY_LISTEN: "0.0.0.0:8000"
    configs:
      - source: kong_config
        target: /etc/kong/kong.yml
    ports:
      - "8100:8000"
      - "8101:8001"
    networks:
      - helpdesk-net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  portainer:
    image: portainer/portainer-ce:lts
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - helpdesk-net
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure

  prometheus:
    image: prom/prometheus:v2.51.0
    volumes:
      - prometheus_data:/prometheus
    configs:
      - source: prometheus_config
        target: /etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - helpdesk-net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  grafana:
    image: grafana/grafana:10.4.0
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana_data:/var/lib/grafana
    configs:
      - source: grafana_datasource
        target: /etc/grafana/provisioning/datasources/prometheus.yml
      - source: grafana_dashboard_provider
        target: /etc/grafana/provisioning/dashboards/dashboards.yml
      - source: grafana_dashboard_helpdesk
        target: /var/lib/grafana/dashboards/helpdesk.json
    ports:
      - "3000:3000"
    networks:
      - helpdesk-net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@helpdesk.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - helpdesk-net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  helpdesk-net:
    driver: overlay


volumes:
  db_data:
  keycloak_data:
  pgadmin_data:
  portainer_data:
  prometheus_data:
  grafana_data:

configs:
  helpdesk_realm:
    file: ./keycloak/helpdesk-realm.json
  kong_config:
    file: ./kong/kong.yml
  prometheus_config:
    file: ./prometheus/prometheus.yml
  grafana_datasource:
    file: ./grafana/provisioning/datasources/prometheus.yml
  grafana_dashboard_provider:
    file: ./grafana/provisioning/dashboards/dashboards.yml
  grafana_dashboard_helpdesk:
    file: ./grafana/dashboards/helpdesk.json
