services:
  auth-service:
    image: helpdesk-distributed-auth-service:latest
    environment:
      KEYCLOAK_URL: http://keycloak:8080
      KEYCLOAK_REALM: helpdesk
    ports:
      - "8001:8001"
    networks:
      - helpdesk-net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  ticket-api:
    image: helpdesk-distributed-ticket-api:latest
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: helpdesk
      POSTGRES_USER: helpdesk
      POSTGRES_PASSWORD: helpdesk

      REDIS_HOST: redis
      REDIS_PORT: 6379

      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: user
      RABBITMQ_PASS: password
    networks:
      - helpdesk-net
    ports:
      - "8000:8000"
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      update_config:
        order: start-first
        parallelism: 1
        delay: 3s


  frontend:
    image: helpdesk-distributed-frontend:latest
    environment:
      AUTH_URL: http://auth-service:8001
      API_URL: http://ticket-api:8000

    networks:
      - helpdesk-net

    ports:
      - "8501:8501"

    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure


  worker:
    image: helpdesk-distributed-worker:latest
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: user
      RABBITMQ_PASS: password
      QUEUE_NAME: ticket_events
      BACKEND_URL: http://ticket-api:8000

    networks:
      - helpdesk-net

    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure


  db:
    image: postgres:15
    environment:
      POSTGRES_DB: helpdesk
      POSTGRES_USER: helpdesk
      POSTGRES_PASSWORD: helpdesk

    volumes:
      - db_data:/var/lib/postgresql/data

    networks:
      - helpdesk-net

    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure


  redis:
    image: redis:7-alpine

    networks:
      - helpdesk-net

    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure


  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

    ports:
      - "5672:5672"
      - "15672:15672"

    networks:
      - helpdesk-net

    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure


  keycloak:
    image: quay.io/keycloak/keycloak:24.0.2
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command:
      - start-dev
      - --import-realm

    ports:
      - "8080:8080"

    volumes:
      - keycloak_data:/opt/keycloak/data
    configs:
      - source: helpdesk_realm
        target: /opt/keycloak/data/import/helpdesk-realm.json

    networks:
      - helpdesk-net

    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure


  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@helpdesk.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - helpdesk-net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  helpdesk-net:
    driver: overlay


volumes:
  db_data:
  keycloak_data:
  pgadmin_data:

configs:
  helpdesk_realm:
    file: ./keycloak/helpdesk-realm.json
